import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
//import 'package:whoyou/screen/home_screen.dart';
import 'screen/auth_wrapper.dart'; // 🔥 Auth wrapper
import 'firebase_options.dart'; // 🔥 Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 🔥 Initialize Firebase with options for all platforms
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const WhoYouApp());
}

class WhoYouApp extends StatelessWidget {
  const WhoYouApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'WhoYou',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1A3A6B)),
        useMaterial3: true,
        fontFamily: 'Roboto',
      ),
      // 🔥 Start with Auth Wrapper
      home: const AuthWrapper(),
    );
  }
}
